[project]
name = "mcpcrew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.114.0",
    "crewai-tools[mcp]>=0.40.1",
    "mcp>=1.6.0",
    "mcpadapt>=0.1.3",
]
